### PR TITLE
Added CMake options to control static/dynamic linking & building

### PR DESCRIPTION
**Pull request by DalenPlanestrider**
I was having issues on Linux Mint with resolving paths to the dynamic libraries on an application that only uses the mariadb client functionality, so I figured I'd just build it all statically.

### CODE REVIEW

**Comment by DalenPlanestrider** [comment]
Sure. I'm contributing this code under the BSD-new license.

As for your suggested change, that'd be better, and I mostly follow the code I think, but I'm not experience enough in cmake to implement it myself.

**Comment by samuaz** [comment]
any news about this?
thanks

**Comment by lawrinn** [comment]
Sorry for not answering - finally preparing new release, so I'm going to finally merge your PR.

**Comment by lawrinn** [comment]
Thanks, I've merged the PR, no I'm gonna change it the way I want it to be

**Comment by Yaksinikos** [comment]
> @lawrinn Hey thanks for be attentive to this, question is there also possibilities to do this for the libmariadb module? Because you can build this as statically but then the libmariadb is shared
> 
> thanks.

I guess, I receive the same issue.
I'm using the mariadbcpp-static.lib, but it seems like there is something missing. 
After adding manually mariadbclient.lib and libmariadb/include the issues are migrating to some other extern symbols, but the in the end I can not use the static lib as a independent lib, as some dependencies seem not to be included.

Did you figured it out?

Screenshot 2024-05-14 172539

**Pull request merged**
